// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV2vkIX2W90_x-7hF2mzxcyd7ZkVwjhI0',
    appId: '1:435790993759:web:6a3c4397e9abc1fd193eea',
    messagingSenderId: '435790993759',
    projectId: 'chatting-app-faaf8',
    authDomain: 'chatting-app-faaf8.firebaseapp.com',
    storageBucket: 'chatting-app-faaf8.firebasestorage.app',
    measurementId: 'G-1HCGFWLJQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpzRtBho4rsk3Wxdlc_U-QVuL14Zq7e60',
    appId: '1:435790993759:android:8f15caa721fd9e46193eea',
    messagingSenderId: '435790993759',
    projectId: 'chatting-app-faaf8',
    storageBucket: 'chatting-app-faaf8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyfCtFvMHNG_f3JEEadB3TaQKnbaXPqUM',
    appId: '1:435790993759:ios:e7ea8e06ab6eade3193eea',
    messagingSenderId: '435790993759',
    projectId: 'chatting-app-faaf8',
    storageBucket: 'chatting-app-faaf8.firebasestorage.app',
    iosBundleId: 'com.example.chattingApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyfCtFvMHNG_f3JEEadB3TaQKnbaXPqUM',
    appId: '1:435790993759:ios:e7ea8e06ab6eade3193eea',
    messagingSenderId: '435790993759',
    projectId: 'chatting-app-faaf8',
    storageBucket: 'chatting-app-faaf8.firebasestorage.app',
    iosBundleId: 'com.example.chattingApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV2vkIX2W90_x-7hF2mzxcyd7ZkVwjhI0',
    appId: '1:435790993759:web:0de662a2ef913770193eea',
    messagingSenderId: '435790993759',
    projectId: 'chatting-app-faaf8',
    authDomain: 'chatting-app-faaf8.firebaseapp.com',
    storageBucket: 'chatting-app-faaf8.firebasestorage.app',
    measurementId: 'G-D8RK44DPKV',
  );
}